### ISSUE TITLE
Memory leak with UC_ARCH_ARM, UC_MODE_ARM + UC_MODE_BIG_ENDIAN

### ISSUE THREAD

**Issue by catenacyber** [unicorn-engine/unicorn#1006]
Can you help me with fixing this memory leak, so we can go in fuzzing ?
I will temporarily subit a pull request to not use this target for the moment.

My guess is that one field is not freed during cleanup.

Traceback from oss-fuzz is 
```
Direct leak of 24576 byte(s) in 1 object(s) allocated from:
    #0 0x4ec317 in calloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:155
    #1 0xa7475c in g_malloc0 /src/unicorn/qemu/glib_compat.c:1231:10
    #2 0x676dab in page_find_alloc_armeb /src/unicorn/qemu/translate-all.c:444:9
    #3 0x675140 in tb_alloc_page_armeb /src/unicorn/qemu/translate-all.c:1352:9
    #4 0x675140 in tb_link_page_armeb /src/unicorn/qemu/translate-all.c:1452
    #5 0x674800 in tb_gen_code_armeb /src/unicorn/qemu/translate-all.c:1127:5
    #6 0x679598 in tb_find_slow_armeb /src/unicorn/qemu/cpu-exec.c:371:10
    #7 0x677639 in cpu_arm_exec_armeb /src/unicorn/qemu/cpu-exec.c:211:22
    #8 0xd1f8d7 in tcg_exec_all_armeb /src/unicorn/qemu/cpus.c:135:17
    #9 0xd1f6de in qemu_tcg_cpu_loop /src/unicorn/qemu/cpus.c:102:13
    #10 0xd1f406 in resume_all_vcpus_armeb /src/unicorn/qemu/cpus.c:76:5
    #11 0xd1f320 in vm_start_armeb /src/unicorn/qemu/cpus.c:46:9
    #12 0x532c2d in uc_emu_start /src/unicorn/qemu/../uc.c:622:9
```

Input code is `\x0a\x0a`

Code is like 
```
    err = uc_open(UC_ARCH_ARM, UC_MODE_THUMB + UC_MODE_BIG_ENDIAN, &uc);
    if (err != UC_ERR_OK) {
        printf("Failed on uc_open() with error returned: %u\n", err);
        abort();
    }

    // map 4MB memory for this emulation
    uc_mem_map(uc, ADDRESS, 4 * 1024 * 1024, UC_PROT_ALL);

    // write machine code to be emulated to memory
    if (uc_mem_write(uc, ADDRESS, "\x0a\x0a", 2)) {
        printf("Failed to write emulation code to memory, quit!\n");
        abort();
    }

    // emulate code in infinite time & 4096 instructions
    // avoid timeouts with infinite loops
    err=uc_emu_start(uc, ADDRESS, ADDRESS + Size, 0, 0x1000);
    if (err) {
        fprintf(outfile, "Failed on uc_emu_start() with error returned %u: %s\n", err, uc_strerror(err));
    }

    uc_close(uc);
```

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10328
