### ISSUE TITLE
Python binding ImportError

### ISSUE THREAD

**Issue by ettermyra** [unicorn-engine/unicorn#1084]
I'm having some problems with the Python bindings of Unicorn, which manifests itself as an ImportError. After successfully installing the core, I've installed the Python bindings both as per instruction from source or by using pip and manually but to no avail using either method. However I think this may just a (relative?) path issue as the test code runs fine within the source python bindings directory where the modules are present but not when "properly" installed in system site-packages.

Error encountered:
```
python -c "import unicorn; print(unicorn.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "unicorn.py", line 3, in <module>
    from unicorn.x86_const import *
ImportError: No module named x86_const
```
The below output is proof of working code when running from ../unicorn-master/bindings/python:
```
./sample_x86.py 
Emulate x86 16-bit code
>>> Emulation done. Below is the CPU context
>>> Read 1 bytes from [0xb] = 0x7
Emulate i386 code
>>> Tracing basic block at 0x1000000, block size = 0x6
>>> Tracing instruction at 0x1000000, instruction size = 0x1
>>> --- EFLAGS is 0x0
>>> Tracing instruction at 0x1000001, instruction size = 0x1
>>> --- EFLAGS is 0x4
>>> Tracing instruction at 0x1000002, instruction size = 0x4
>>> --- EFLAGS is 0x10
>>> Emulation done. Below is the CPU context
>>> ECX = 0x1235
>>> EDX = 0x788f
>>> XMM0 = 0x00112233445566778899aabbccddeeff
>>> Read 4 bytes from [0x1000000] = 0xf664a41
...
```

Running Fedora 29 - Kernel 5.0.7-200.fc29.x86_64
Python 2.7.15 and 3.7.3 (same error in either of them)

Python module installations and import system is not my forte...Any insights and tips?

Thanks!

**Comment by ettermyra** [comment]
Reverted to Fedora packages instead. However I prefer to be able to install from source in this case.
