### ISSUE TITLE
AttributeError: dlsym(0x7fdee3406d60, uc_context_size): symbol not found

### ISSUE THREAD

**Issue by liumengdeqq** [unicorn-engine/unicorn#1162]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
  File "unicorn/unicorn.py", line 141, in <module>
    _setup_prototype(_uc, "uc_context_size", ctypes.c_size_t, uc_engine)
  File "unicorn/unicorn.py", line 103, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fdee3406d60, uc_context_size): symbol not found

**Comment by 2simple** [comment]
I got the same problem, do you resolved it?

**Comment by 2simple** [comment]
> Traceback (most recent call last):
> File "", line 1, in
> File "unicorn/**init**.py", line 4, in
> from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, **version**
> File "unicorn/unicorn.py", line 141, in
> _setup_prototype(_uc, "uc_context_size", ctypes.c_size_t, uc_engine)
> File "unicorn/unicorn.py", line 103, in _setup_prototype
> getattr(lib, fname).restype = restype
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/**init**.py", line 379, in **getattr**
> func = self.**getitem**(name)
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/**init**.py", line 384, in **getitem**
> func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: dlsym(0x7fdee3406d60, uc_context_size): symbol not found

I got the same problem, do you resolved it

**Comment by bmax121** [comment]
File "/Users/xxx/workspace/github/angr-dev/angr/setup.py", line 52, in _build_native
        import unicorn
      File "/Users/xxx/workspace/pyvenv/angrdev/lib/python3.8/site-packages/unicorn/__init__.py", line 4, in <module>
        from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
      File "/Users/xxx/workspace/pyvenv/angrdev/lib/python3.8/site-packages/unicorn/unicorn.py", line 141, in <module>
        _setup_prototype(_uc, "uc_context_size", ctypes.c_size_t, uc_engine)
      File "/Users/xxx/workspace/pyvenv/angrdev/lib/python3.8/site-packages/unicorn/unicorn.py", line 103, in _setup_prototype
        getattr(lib, fname).restype = restype
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
        func = self.__getitem__(name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(0x7ff6cacc1ff0, uc_context_size): symbol not found

**Comment by cecini** [comment]
Just build from source, brew binary unicorn is conflict with the python package.

**Comment by 745198699** [comment]
> Just build from source, brew binary unicorn is conflict with the python package.

I still got the same problem...

MacOSX 10.14.6
Python 3.8.5
unicorn 1.0.2

Did i do something wrong? Steps:
$ ./make.sh
$ sudo ./make.sh install
$ cd bindings/python
$ sudo python3 setup.py install
