### ISSUE TITLE
UC_ERR_INSN_INVALID - on armv8 binary - using qiling

### ISSUE THREAD

**Issue by zi0Black** [unicorn-engine/unicorn#1343]
I got this error "unicorn.unicorn.UcError: Invalid instruction (UC_ERR_INSN_INVALID)" trying to emulate a binary from an IoT device.
The architecture should be "armv8 64bit thumb".
The PC value at the time of the crash was "0x7757c4c8" and "libcrypto.so" is loaded there "77539000 - 7769c000", so I decompiled it and I have done some hex math [python: hex(0x7757c4c8 - 0x77539000)], and at this "'0x434c8'" offset I should find the "invalid" instruction.
This is what I found (see the following image):
![image](https://user-images.githubusercontent.com/13380579/95868332-63fab000-0d6a-11eb-92c5-292e12ce7a27.png)

Can you confirm that this instruction is not implemented?

Full stack trace:
```
rt_sigprocmask(0x2, 0x7ff3c7d8, 0x7ff3c7b0, 0x8) = 0
rt_sigaction(0x4, 0x7ff3c77c, = 0x7ff3c7b8) = 0
rt_sigprocmask(0x0, 0x0, 0x776bff6c, 0x8) = 0
rt_sigprocmask(0x0, 0x0, 0x776bff6c, 0x8) = 0
[!] Emulation Error

[-] r0  :        0x0
[-] r1  :        0x0
[-] r2  :        0x776bff6c
[-] r3  :        0x8
[-] r4  :        0x776bfe68
[-] r5  :        0x7ff3c7cc
[-] r6  :        0x1
[-] r7  :        0x0
[-] r8  :        0x776bff84
[-] r9  :        0x776b9964
[-] r10 :        0x7ff3cd78
[-] r11 :        0x7ff3c80c
[-] r12 :        0x776bfe90
[-] sp  :        0x7ff3c7a8
[-] lr  :        0x77578658
[-] pc  :        0x7757c4c8
[-] cpsr        :        0x600001d3
[-] c1_c0_2     :        0xf00000
[-] c13_c0_3    :        0x77b057b0
[-] fpexc       :        0x40000000

[+] PC = 0x7757c4c8
[+] Start      End        Perm.  Path
[+] 047ba000 - 047d2000 - rwx    /lib/ld-uClibc.so.0
[+] 56555000 - 56617000 - r-x    /root/usr/bin/cwmp.kia (/root/usr/bin/cwmp.kia)
[+] 56627000 - 5662e000 - rw-    /root/usr/bin/cwmp.kia (/root/usr/bin/cwmp.kia)
[+] 5662e000 - 566a5000 - rwx    /root/usr/bin/cwmp.kia (/root/usr/bin/cwmp.kia)
[+] 566a5000 - 566a7000 - rwx    [hook_mem] (/root/usr/bin/cwmp.kia)
[+] 566a7000 - 566a8000 - rwx    [brk]
[+] 566a8000 - 566ad000 - rwx    [brk]
[+] 774bf000 - 774c0000 - rwx    [syscall_mmap2]
[+] 774c1000 - 774c3000 - rwx    [mmap2] /root/lib/libssp.so.0.0.0
[+] 774c3000 - 774d2000 - rwx    [syscall_mmap2]
[+] 774d2000 - 774d3000 - rwx    [mmap2] /root/lib/libssp.so.0.0.0
[+] 774d4000 - 77523000 - rwx    [mmap2] /root/usr/lib/libssl.so.1.0.0
[+] 77523000 - 77532000 - rwx    [syscall_mmap2]
[+] 77532000 - 77538000 - rwx    [mmap2] /root/usr/lib/libssl.so.1.0.0
[+] 77539000 - 7769c000 - rwx    [mmap2] /root/usr/lib/libcrypto.so.1.0.0
[+] 7769c000 - 776ac000 - rwx    [syscall_mmap2]
[+] 776ac000 - 776c0000 - rwx    [mmap2] /root/usr/lib/libcrypto.so.1.0.0
[+] 776c0000 - 776c2000 - rwx    [syscall_mmap2]
[+] 776c3000 - 776c6000 - rwx    [mmap2] /root/usr/lib/libseccrypto.so
[+] 776c6000 - 776d5000 - rwx    [syscall_mmap2]
[+] 776d5000 - 776d6000 - rwx    [mmap2]/root/usr/lib/libseccrypto.so
[+] 776d7000 - 776fc000 - rwx    [mmap2] /root/usr/lib/libnetutil.so
[+] 776fc000 - 7770b000 - rwx    [syscall_mmap2]
[+] 7770b000 - 7770c000 - rwx    [mmap2] /root/usr/lib/libnetutil.so
[+] 7770d000 - 77768000 - rwx    [mmap2] /root/usr/lib/libmfl.so
[+] 77768000 - 77778000 - rwx    [syscall_mmap2]
[+] 77778000 - 7777e000 - rwx    [mmap2] /root/usr/lib/libmfl.so
[+] 7777f000 - 77863000 - rwx    [mmap2] /root/usr/lib/libstdc++.so.6.0.21
[+] 77863000 - 77872000 - rwx    [syscall_mmap2]
[+] 77872000 - 7787a000 - rwx    [mmap2] /root/usr/lib/libstdc++.so.6.0.21
[+] 7787a000 - 7787c000 - rwx    [syscall_mmap2]
[+] 7787d000 - 7788d000 - rwx    [mmap2] /root/lib/libpthread-1.0.14.so
[+] 7788d000 - 7789c000 - rwx    [syscall_mmap2]
[+] 7789c000 - 7789e000 - rwx    [mmap2] /root/lib/libpthread-1.0.14.so
[+] 7789e000 - 778a0000 - rwx    [syscall_mmap2]
[+] 778a1000 - 778a6000 - rwx    [mmap2] /root/usr/lib/libsys.so
[+] 778a6000 - 778b6000 - rwx    [syscall_mmap2]
[+] 778b6000 - 778b7000 - rwx    [mmap2] /root/usr/lib/libsys.so
[+] 778b8000 - 778bb000 - rwx    [mmap2] root/lib/librt-1.0.14.so
[+] 778bb000 - 778ca000 - rwx    [syscall_mmap2]
[+] 778ca000 - 778cc000 - rwx    [mmap2] /root/lib/librt-1.0.14.so
[+] 778cd000 - 778d2000 - rwx    [mmap2] /root/lib/libcrypt-1.0.14.so
[+] 778d2000 - 778e1000 - rwx    [syscall_mmap2]
[+] 778e1000 - 778e3000 - rwx    [mmap2] /root/lib/libcrypt-1.0.14.so
[+] 778e3000 - 778f4000 - rwx    [syscall_mmap2]
[+] 778f4000 - 778f5000 - rwx    [syscall_mmap2]
[+] 778f6000 - 77904000 - rwx    [mmap2] /root/lib/libm-1.0.14.so
[+] 77904000 - 77913000 - rwx    [syscall_mmap2]
[+] 77913000 - 77915000 - rwx    [mmap2] /root/lib/libm-1.0.14.so
[+] 77916000 - 77a0f000 - rwx    [mmap2] /root/usr/lib/libxml2.so.2.9.2
[+] 77a0f000 - 77a1e000 - rwx    [syscall_mmap2]
[+] 77a1e000 - 77a23000 - rwx    [mmap2] /root/usr/lib/libxml2.so.2.9.2
[+] 77a23000 - 77a24000 - rwx    [syscall_mmap2]
[+] 77a25000 - 77a2d000 - rwx    [mmap2] /root/lib/libuci.so
[+] 77a2d000 - 77a3c000 - rwx    [syscall_mmap2]
[+] 77a3c000 - 77a3e000 - rwx    [mmap2] /root/lib/libuci.so
[+] 77a3f000 - 77a47000 - rwx    [mmap2] /root/lib/libubox.so
[+] 77a47000 - 77a56000 - rwx    [syscall_mmap2]
[+] 77a56000 - 77a58000 - rwx    [mmap2] /root/lib/libubox.so
[+] 77a59000 - 77a64000 - rwx    [mmap2] /root/lib/libgcc_s.so.1
[+] 77a64000 - 77a73000 - rwx    [syscall_mmap2]
[+] 77a73000 - 77a74000 - rwx    [mmap2] /root/lib/libgcc_s.so.1
[+] 77a75000 - 77ac5000 - rwx    [mmap2] /root/lib/libuClibc-1.0.14.so
[+] 77ac5000 - 77ac7000 - rwx    [mmap2] /root/lib/libuClibc-1.0.14.so
[+] 77ac7000 - 77aca000 - rwx    [syscall_mmap2]
[+] 77acb000 - 77ace000 - rwx    [mmap2] /root/lib/libdl-1.0.14.so
[+] 77ace000 - 77add000 - rwx    [syscall_mmap2]
[+] 77add000 - 77adf000 - rwx    [mmap2] /root/lib/libdl-1.0.14.so
[+] 77ae0000 - 77af5000 - rwx    [mmap2] /root/lib/libz.so.1.2.8
[+] 77af5000 - 77b04000 - rwx    [syscall_mmap2]
[+] 77b04000 - 77b05000 - rwx    [mmap2] /root/lib/libz.so.1.2.8
[+] 77b05000 - 77b06000 - rwx    [syscall_mmap2]
[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[+] ffff0000 - ffff1000 - rwx    [arm_tls]
[+] ['0x0', '0xe', '0xa0', '0xf2', '0x1e', '0xff', '0x2f', '0xe1']

[+] 0x7757c4c8     00 0e a0 f2 1e ff 2f e1 68 00 9f e5 64 10 8f e2 00 00 91 e7 02 20 22 e0 03 30 23 e0 0c c0 2c e0 01 00 10 e3 0b 00 00 0a 50 01 00 f3 52 21 02 f3 54 41 04 f3 56 61 06 f3 f0 01 40 f3 f2 21 42 f3 Traceback (most recent call last):
  File "run.py", line 73, in <module>
    my_net(["root/usr/bin/cwmp.kia",
  File "run.py", line 69, in my_net
    ql.run()
  File "/home/zi0black/.local/lib/python3.8/site-packages/qiling/core.py", line 198, in run
    self.os.run()
  File "/home/zi0black/.local/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 101, in run
    thread_management.run()
  File "/home/zi0black/.local/lib/python3.8/site-packages/qiling/os/linux/thread.py", line 455, in run
    self.runing_time += self.cur_thread.run(bbl_slice = thread_slice, mode = BBL_MODE)
  File "/home/zi0black/.local/lib/python3.8/site-packages/qiling/os/linux/thread.py", line 132, in run
    self.ql.emu_start(self.start_address, self.exit_point)
  File "/home/zi0black/.local/lib/python3.8/site-packages/qiling/core.py", line 257, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/home/zi0black/.local/lib/python3.8/site-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid instruction (UC_ERR_INSN_INVALID)
```

**Comment by aquynh** [comment]
yes. Unicorn2 would solve the problem:
https://github.com/unicorn-engine/unicorn/issues/1217

**Comment by zi0Black** [comment]
Could you give me some indication of where to look in the Qemu source code to understand where and how assembly instructions are implemented?
