### ISSUE TITLE
Some AES-NI instrctions are regarded as invalid instruction

### ISSUE THREAD

**Issue by bigmangoobyy** [unicorn-engine/unicorn#1513]
Hello,
I ‘d like to use unicorn to emulate openssl, but I found that some aes-ni instructions like **sha1msg1, sha1rnds4** cause errors in unicorn, here is my code:
```
from unicorn import *
from unicorn.x86_const import *

# X86_CODE64_ENC = b"\x66\x0F\x38\xDC\xD0" 
# X86_CODE64_SHA = b"\x45\x0F\x3A\xCC\xC1\x00"
X86_CODE64_SHA = b"\x0F\x38\xC9\xDC" # sha1msg1 xmm3,xmm4
ADDRESS = 0x1000000


def TestENC():
    mu = Uc(UC_ARCH_X86, UC_MODE_64)
    mu.mem_map(ADDRESS, 2 * 1024 * 1024)
    mu.mem_write(ADDRESS, X86_CODE64_SHA)
    mu.reg_write(UC_X86_REG_RAX, 0x71f3029efd49d41d)
    mu.reg_write(UC_X86_REG_RBX, 0xd87b45277f133ddb)
    mu.reg_write(UC_X86_REG_RCX, 0xab40d1ffd8afc461)
    mu.reg_write(UC_X86_REG_RDX, 0x919317b4a733f01)
    mu.reg_write(UC_X86_REG_RSI, 0x4c24e753a17ea358)
    mu.reg_write(UC_X86_REG_RDI, 0xe509a57d2571ce96)
    mu.reg_write(UC_X86_REG_R8, 0xea5b108cc2b9ab1f)
    mu.reg_write(UC_X86_REG_R9, 0x19ec097c8eb618c1)
    mu.reg_write(UC_X86_REG_R10, 0xec45774f00c5f682)
    mu.reg_write(UC_X86_REG_R11, 0xe17e9dbec8c074aa)
    mu.reg_write(UC_X86_REG_R12, 0x80f86a8dc0f6d457)
    mu.reg_write(UC_X86_REG_R13, 0x48288ca5671c5492)
    mu.reg_write(UC_X86_REG_R14, 0x595f72f6e4017f6e)
    mu.reg_write(UC_X86_REG_R15, 0x1efd97aea331cccc)
    mu.reg_write(UC_X86_REG_RSP, ADDRESS + 0x200000)
    mu.reg_write(UC_X86_REG_XMM0, 0x000102030405060708090a0b0c0d0e0f)
    mu.reg_write(UC_X86_REG_XMM2, 0x000102030405060708090a0b0c0d0e0f)
    mu.reg_write(UC_X86_REG_XMM8, 0x000102030405060708090a0b0c0d0e0f)
    mu.reg_write(UC_X86_REG_XMM9, 0x000102030405060708090a0b0c0d0e0f)
    mu.reg_write(UC_X86_REG_XMM3, 0x000102030405060708090a0b0c0d0e0f)
    mu.reg_write(UC_X86_REG_XMM4, 0x000102030405060708090a0b0c0d0e0f)
    mu.emu_start(ADDRESS, ADDRESS + len(X86_CODE64_SHA))
    xmm4 = mu.reg_read(UC_X86_REG_XMM4)
    xmm3 = mu.reg_read(UC_X86_REG_XMM3)
    print(">>> xmm8=0x%x" % xmm3)
    print(">>> xmm9=0x%x" % xmm4)

TestENC()
```
But I got errors like this:
```
Traceback (most recent call last):
  File "unicorntest.py", line 42, in <module>
    TestENC()
  File "unicorntest.py", line 35, in TestENC
    mu.emu_start(ADDRESS, ADDRESS + len(X86_CODE64_SHA))
  File "/home/mangoo/miniconda3/envs/angr/lib/python3.8/site-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid instruction (UC_ERR_INSN_INVALID)

```
Are these instructions supported by unicorn? Thanks.

**Comment by aquynh** [comment]
Did you try with "dev" branch?

**Comment by bigmangoobyy** [comment]
> Did you try with "dev" branch?

Sorry for the late reply. I tried with the "dev" branch, but  still get the same error.

**Comment by wtdcode** [comment]
> > Did you try with "dev" branch?
> 
> Sorry for the late reply. I tried with the "dev" branch, but still get the same error.

Thanks for your feedback and I would have a look.

**Comment by wtdcode** [comment]
Unfortunately, even the latest qemu doesn't support the Intel SHA extension. At this moment, we have nothing more to do.
