### ISSUE TITLE
Trying to read UC_X86_REG_MSR throws an error, working as intended?

### ISSUE THREAD

**Issue by jt0dd** [unicorn-engine/unicorn#1518]
I noticed UC_X86_REG_MSR is a constant Unicorn exposes, but it's the only `UC_x86_REG_` constant that if you try to call the `reg_read` method on it, throws an error. I was building a function to enumerate the registers:

```
# Keystone
# The Ultimate Assembler
from keystone import *

# Capstone
# The Ultimate Disassembler
from capstone import *

# Unicorn
# The ultimate CPU emulator
import unicorn
from unicorn import *
from unicorn.x86_const import *

from pprint import pprint

ks = Ks(KS_ARCH_X86, KS_MODE_64)
ks.syntax = KS_OPT_SYNTAX_ATT
md = Cs(CS_ARCH_X86, CS_MODE_64)
mu = Uc(UC_ARCH_X86, UC_MODE_64)

# enumerate registers
reg_keys = []
constants = dir(unicorn.x86_const)
for val in constants:
	if val[0:10] == 'UC_X86_REG':
	        mu.reg_read(unicorn.x86_const.__getattribute__(val))
	        reg_keys.append(val)
```

Output:

```
Traceback (most recent call last):
  File "transform.py", line 52, in <module>
    mu.reg_read(unicorn.x86_const.__getattribute__(val))
  File "/home/defender/.local/lib/python3.8/site-packages/unicorn/unicorn.py", line 478, in reg_read
    return reg_read(functools.partial(_uc.uc_reg_read, self._uch), self._arch, reg_id, opt)
  File "/home/defender/.local/lib/python3.8/site-packages/unicorn/unicorn.py", line 256, in reg_read
    raise UcError(uc.UC_ERR_ARG)
unicorn.unicorn.UcError: Invalid argument (UC_ERR_ARG)
```

So I had to go with:

```
for val in constants:
	if val[0:10] == 'UC_X86_REG':
		try:
			mu.reg_read(unicorn.x86_const.__getattribute__(val))
			reg_keys.append(val)
		except:
			print('skipped reg:', val)
```

and this results in only skipping `UC_X86_REG_MSR` with the rest of the registers behaving as expected.

**Comment by wtdcode** [comment]
I suspect it's due to constants not updated for Unicorn. What's your `pip freeze` outputs?

**Comment by jt0dd** [comment]
unicorn==2.0.0rc5.post1

**Comment by wtdcode** [comment]
It's the similar reason as #1517. You have to use `msr_read` wrapper here:

https://github.com/unicorn-engine/unicorn/blob/3184d3fcdf239c77857faacf5670d5b2d64a69cd/bindings/python/unicorn/unicorn.py#L485
