### ISSUE TITLE
Unable to read ARM64 v or q register using java binding

### ISSUE THREAD

**Issue by xmaxxaa** [unicorn-engine/unicorn#1539]
Host : macOS 11.6.2
Jdk : tried openjdk 8 and openjdk 11
Unicorn  version : unicorn-2.0.0-rc5
Both c and python codes work fine:
```c
    // c
    uc_engine *uc;
    int64_t r_result;
    int64_t r = 0x123;
    uc_open(UC_ARCH_ARM64, UC_MODE_ARM, &uc);
    uc_reg_write(uc, UC_ARM64_REG_V0, &r);
    uc_reg_read(uc, UC_ARM64_REG_V0, &r_result);
    printf("r_result: %llx\n", r_result);
```
```python
    # python
    uc = unicorn.Uc(unicorn.UC_ARCH_ARM64, unicorn.UC_MODE_ARM)
    uc.reg_write(unicorn.arm64_const.UC_ARM64_REG_V0, 1)
    result = uc.reg_read(unicorn.arm64_const.UC_ARM64_REG_V0, 1)
    print(result)
```
And java code just crashed:
```java
    public static void main(String[] args) {
        Unicorn uc = new Unicorn(Unicorn.UC_ARCH_ARM64, Unicorn.UC_MODE_ARM);
        uc.reg_write(Unicorn.UC_ARM64_REG_X0, 0x1); // works fine
        uc.reg_write(Unicorn.UC_ARM64_REG_V0, 0x2); // works fine
        uc.reg_read(Unicorn.UC_ARM64_REG_X0); // works fine
        uc.reg_read(Unicorn.UC_ARM64_REG_V0); // exception
    }
```
crash log:
```
V  [libjvm.dylib+0x2f86e9]  alloc_object(_jclass*, Thread*)+0x25
V  [libjvm.dylib+0x2f900b]  jni_NewObject+0xed
C  [libunicorn_java.dylib+0x15bf]  Java_unicorn_Unicorn_reg_1read_1num+0xdf
j  unicorn.Unicorn.reg_read_num(I)Ljava/lang/Number;+0
j  unicorn.Unicorn.reg_read(I)Ljava/lang/Object;+30
j  com.xxx.Main.main([Ljava/lang/String;)V+25
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x2c3812]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x688
V  [libjvm.dylib+0x2ff600]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x259
V  [libjvm.dylib+0x301fa6]  jni_CallStaticVoidMethod+0x174
C  [java+0x667a]  JavaMain+0x9d3
C  [libsystem_pthread.dylib+0x68fc]  _pthread_start+0xe0
C  [libsystem_pthread.dylib+0x2443]  thread_start+0xf
```
I add some logs in jni function ``Java_unicorn_Unicorn_reg_1read_1num``:
```c
JNIEXPORT jobject JNICALL Java_unicorn_Unicorn_reg_1read_1num
  (JNIEnv *env, jobject self, jint regid) {
   uc_engine *eng = getEngine(env, self);
   jclass clz = (*env)->FindClass(env, "java/lang/Long");
   if ((*env)->ExceptionCheck(env)) {
      return NULL;
   }

   jlong longVal;
   uc_err err = uc_reg_read(eng, regid, &longVal);
   // add
   printf("Java_unicorn_Unicorn_reg_1read_1num longVal: %lx\n", longVal);
   if (err != UC_ERR_OK) {
      throwException(env, err);
   }

   jmethodID cons = (*env)->GetMethodID(env, clz, "<init>", "(J)V");
   // add
   printf("Java_unicorn_Unicorn_reg_1read_1num jmethodID: %p\n", cons);
   jobject result = (*env)->NewObject(env, clz, cons, longVal);
   if ((*env)->ExceptionCheck(env)) {
      return NULL;
   }
   return result;
}
```
The output is weird, ``jmethodID`` is **NULL** when read v register:
```
Exception in thread "main" java.lang.InstantiationException
	at unicorn.Unicorn.reg_read_num(Native Method)
	at unicorn.Unicorn.reg_read(Unicorn.java:464)
	at com.xxx.Main.main(Main.java:12)
Java_unicorn_Unicorn_reg_1read_1num longVal: 1 // uc.reg_read(Unicorn.UC_ARM64_REG_X0);
Java_unicorn_Unicorn_reg_1read_1num jmethodID: 0x7fd4dad18a68
Java_unicorn_Unicorn_reg_1read_1num longVal: 2 // uc.reg_read(Unicorn.UC_ARM64_REG_V0);
Java_unicorn_Unicorn_reg_1read_1num jmethodID: 0x0
```

**Comment by wtdcode** [comment]
Hello, unfortunately, I'm not familiar with Java bindings and I think it's not actively maintained for a while.

You might send a PR for this.
