### ISSUE TITLE
Memory leak in test_mem_protect_map_ptr

### ISSUE THREAD

**Issue by relapids** [unicorn-engine/unicorn#1682]
Not a big deal since it's only in test code, but figured I may as well report it.

Steps to reproduce: Build with LeakSanitizer (enabled by default with AddressSanitizer on Linux) and run the tests/samples.

Example build steps:
```
$ cmake -S ../repo/ -B . -G Ninja -D CMAKE_C_COMPILER=clang -D CMAKE_C_FLAGS=-fsanitize=address -D CMAKE_BUILD_TYPE=Debug
$ cmake --build .
```

Output for test_mem_protect_map_ptr:
```
Test test_mem_protect_map_ptr...                [ OK ]

=================================================================
==7103==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x55feef15e421 in __interceptor_calloc (/home/builder/unicorn/build/test_mem+0xdc421)
    #1 0x55feef1a8b16 in test_mem_protect_map_ptr /home/builder/unicorn/repo/tests/unit/test_mem.c:129:13
    #2 0x55feef1abd86 in acutest_do_run_ /home/builder/unicorn/repo/tests/unit/acutest.h:1026:9
    #3 0x55feef1a6293 in acutest_run_ /home/builder/unicorn/repo/tests/unit/acutest.h:1124:23
    #4 0x55feef1a388e in main /home/builder/unicorn/repo/tests/unit/acutest.h:1831:13
    #5 0x7fbc508742cf  (/usr/lib/libc.so.6+0x232cf) (BuildId: e637217a46491314667a7a37b2155cb07afc1a40)

Direct leak of 8192 byte(s) in 1 object(s) allocated from:
    #0 0x55feef15e421 in __interceptor_calloc (/home/builder/unicorn/build/test_mem+0xdc421)
    #1 0x55feef1a8b29 in test_mem_protect_map_ptr /home/builder/unicorn/repo/tests/unit/test_mem.c:130:13
    #2 0x55feef1abd86 in acutest_do_run_ /home/builder/unicorn/repo/tests/unit/acutest.h:1026:9
    #3 0x55feef1a6293 in acutest_run_ /home/builder/unicorn/repo/tests/unit/acutest.h:1124:23
    #4 0x55feef1a388e in main /home/builder/unicorn/repo/tests/unit/acutest.h:1831:13
    #5 0x7fbc508742cf  (/usr/lib/libc.so.6+0x232cf) (BuildId: e637217a46491314667a7a37b2155cb07afc1a40)

SUMMARY: AddressSanitizer: 24576 byte(s) leaked in 2 allocation(s).
```

The two (test local) allocations (data1 & data2) in test_mem_protect_map_ptr are not freed.

```
    data1 = calloc(sizeof(*data1), 0x4000);
    data2 = calloc(sizeof(*data2), 0x2000);
```

**Comment by wtdcode** [comment]
Closed as fixed.
