### ISSUE TITLE
Segmentation fault in tb_set_jmp_target_mipsel

### ISSUE THREAD

**Issue by liona24** [unicorn-engine/unicorn#1702]
Hey.

The current version of unicorn shipped with a default pip install on linux may segfault in tb_set_jmp_target_mipsel.

Stack trace:
```
#0  0x00007fdacb094ff1 in tb_set_jmp_target_mipsel () from /lib64/python3.10/site-packages/unicorn/lib/libunicorn.so.2
#1  0x00007fdacb09532d in cpu_exec_mipsel () from /lib64/python3.10/site-packages/unicorn/lib/libunicorn.so.2
#2  0x00007fdacb05afc4 in resume_all_vcpus_mipsel () from /lib64/python3.10/site-packages/unicorn/lib/libunicorn.so.2
#3  0x00007fdac97908db in uc_emu_start (uc=0x5654dacfa270, begin=<optimized out>, until=0x400c3c, timeout=0x0, count=0x0) at /fuzz/third_party/unicorn/uc.c:870
...
```

Disassembly:
```
Dump of assembler code for function tb_set_jmp_target_mipsel:
   0x00007fdacb094fe0 <+0>:     movsxd rsi,esi
   0x00007fdacb094fe3 <+3>:     mov    rax,QWORD PTR [rdi+0x18]
   0x00007fdacb094fe7 <+7>:     sub    edx,0x4
   0x00007fdacb094fea <+10>:    add    rax,QWORD PTR [rdi+rsi*8+0x58]
   0x00007fdacb094fef <+15>:    sub    edx,eax
=> 0x00007fdacb094ff1 <+17>:    mov    DWORD PTR [rax],edx
   0x00007fdacb094ff3 <+19>:    ret    
```

Register Dump:
```
rax            0x0                 0x0
rbx            0x5654dad13310      0x5654dad13310
rcx            0x7fda89108100      0x7fda89108100
rdx            0x891080fc          0x891080fc
rsi            0x0                 0x0
rdi            0x7fda89108400      0x7fda89108400
rbp            0x0                 0x0
rsp            0x7fffaae740f8      0x7fffaae740f8
r8             0x1                 0x1
r9             0x816c3709          0x816c3709
r10            0x7fda89108040      0x7fda89108040
r11            0x5654dad07cbc      0x5654dad07cbc
r12            0x7fda89108040      0x7fda89108040
r13            0x0                 0x0
r14            0x400c2c            0x400c2c
r15            0x7fda89108400      0x7fda89108400
rip            0x7fdacb094ff1      0x7fdacb094ff1 <tb_set_jmp_target_mipsel+17>
eflags         0x10286             [ PF SF IF RF ]
cs             0x33                0x33
ss             0x2b                0x2b
ds             0x0                 0x0
es             0x0                 0x0
fs             0x0                 0x0
gs             0x0                 0x0
```

This happens during a reset loop after a couple thousand invocations. The binary is compiled for mips32el:
```
ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), statically linked, BuildID[sha1]=59867c45156f0bf2bd37ffa32e07e788a1163bfb, for GNU/Linux 3.2.0, not stripped
```
If you have any tips on debugging this, I will gladly provide more details.

Hopefully I can attach a reproducer later, my current setup produces this crash consistently

**Comment by liona24** [comment]
Actually I am not sure if this is a user error (me).
The problem is resolved when using the `uc_context_restore` before each invocation of `uc_emu_start`. Is `uc_emu_start` not supposed to be called repeatedly?

**Comment by PhilippTakacs** [comment]
Can you provide a reproduction script?

**Comment by liona24** [comment]
I can reproduce this consistently using the following:
- Checkout this commit of the project I was working on:
```bash
git clone https://github.com/liona24/unicorn-fuzz.git
git checkout 9b87541d66fbce9f56c742dfcf8adf93fccb29ea
```
- Build according to instructions in README and setup python venv
- `python3 examples/mips/int_overflow.py -s examples/mips/_dump_int_overflow_mips32el.json`
- Wait for ~5 Minutes

If you want to get a core you have to fix the argument passing in the `int_overflow.py:51` script and use the following:
```
python3 examples/mips/int_overflow.py -s examples/mips/_dump_int_overflow_mips32el.json -- -handle_abrt=0 -handle_segv=0 -handle_int=0 -handle_ill=0
```

If you have any trouble with this setup please let me know.

**Comment by PhilippTakacs** [comment]
It would be nice if you could provide a smaller example. I'm not familiar with your code.

**Comment by wtdcode** [comment]
It seems hard to reproduce but I have some thought about it. Probably #1635
