### ISSUE TITLE
Building unicorn from source on Alpine fails with `/home/venom/mtkclient/unicorn/qemu/util/oslib-posix.c:33:10: fatal error: linux/mman.h: No such file or directory`

### ISSUE THREAD

**Issue by VenomousSteam81** [unicorn-engine/unicorn#1965]
I'm trying to build unicorn from source for mtkclient on Alpine because I get an error from it and multiple other packages.
The error I'm getting from building from source is:

```
/home/venom/mtkclient/unicorn/qemu/util/oslib-posix.c:33:10: fatal error: linux/mman.h: No such file or directory
   33 | #include <linux/mman.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/unicorn-common.dir/build.make:440: CMakeFiles/unicorn-common.dir/qemu/util/oslib-posix.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:591: CMakeFiles/unicorn-common.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

Output of `/etc/os-release`:
```
PRETTY_NAME="postmarketOS v24.06"
NAME="postmarketOS"
VERSION_ID="v24.06"
VERSION="v24.06"
ID="postmarketos"
ID_LIKE="alpine"
HOME_URL="https://www.postmarketos.org/"
SUPPORT_URL="https://gitlab.com/postmarketOS"
BUG_REPORT_URL="https://gitlab.com/postmarketOS/pmaports/issues"
LOGO="postmarketos-logo"
```
If you want the errors I get from using `pip3 install unicorn`, I will be glad to give them.

**Comment by VenomousSteam81** [comment]
Ok, I just ran `pip3 install unicorn` again and realized that I get the same errors.

<details><summary>Details</summary>
<p>
      /tmp/pip-install-1f5i0r2w/unicorn_86301900b68e42ab8e8dc11c35b9935d/src/qemu/util/oslib-posix.c:33:10: fatal error: linux/mman.h: No such file or directory
         33 | #include <linux/mman.h>
            |          ^~~~~~~~~~~~~~
      compilation terminated.
      gmake[2]: *** [CMakeFiles/unicorn-common.dir/build.make:440: CMakeFiles/unicorn-common.dir/qemu/util/oslib-posix.c.o] Error 1
      gmake[2]: *** Waiting for unfinished jobs....
      gmake[1]: *** [CMakeFiles/Makefile2:591: CMakeFiles/unicorn-common.dir/all] Error 2
      gmake: *** [Makefile:146: all] Error 2
      Traceback (most recent call last):
        File "/home/venom/mtkclient/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/venom/mtkclient/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/venom/mtkclient/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 232, in <module>
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9idwzatz/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 164, in run
        File "<string>", line 144, in build_libraries
        File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j4']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
</p>
</details>

**Comment by VenomousSteam81** [comment]
I guess `apk add py3-(pip3 package that couldnt be installed)` works. Might not be as stable, but I will try it.

**Comment by wtdcode** [comment]
Sorry just notice this thread. How to reproduce? Does an alpine docker repro this?

**Comment by wtdcode** [comment]
Closing as solution attached and workflow added.
