### ISSUE TITLE
Exceptions handled incorrectly in python callback functions

### ISSUE THREAD

**Issue by mrj0n3s** [unicorn-engine/unicorn#1987]
Tested with Python 3.8

```python
import binascii
from unicorn import Uc, UC_HOOK_CODE, UC_ARCH_X86, UC_MODE_64

def code_hook(mu, address, size, value):
    print(1/0)
    return True
       
uc = Uc(UC_ARCH_X86, UC_MODE_64)
uc.hook_add(UC_HOOK_CODE, code_hook)

code = binascii.unhexlify('C3')
addr = 0
uc.mem_map(0, 0x1000)
uc.mem_write(addr, code)
uc.emu_start(addr, addr + len(code), count=1)
```

Expected behavior
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    uc.emu_start(addr, addr + len(code), count=1)
  File "/home/unicorn/.local/lib/python3/site-packages/unicorn/unicorn.py", line 550, in emu_start
    raise self._hook_exception
  File "/home/unicorn/.local/lib/python3/site-packages/unicorn/unicorn.py", line 392, in wrapper
    return func(self, *args, **kwargs)
  File "/home/unicorn/.local/lib/python3/site-packages/unicorn/unicorn.py", line 663, in _hookcode_cb
    cb(self, address, size, data)
  File "test.py", line 5, in code_hook
    print(1/0)
ZeroDivisionError: division by zero
```

Dev branch behavior
```Exception ignored on calling ctypes callback function: <function Uc.hook_add.<locals>.__hook_code.<locals>.__hook_code_cb at 0x7f33100c2a60>
Traceback (most recent call last):
  File "/home/unicorn/.local/lib/python3/site-packages/unicorn/unicorn_py3/unicorn.py", line 302, in wrapper
    if uc._hook_exception is None:
AttributeError: 'int' object has no attribute '_hook_exception'
```

**Comment by wtdcode** [comment]
Fixed in 78cb4affdaabf0ec0cee5e06d3e57560f1a0b8c2
