### ISSUE TITLE
Unicorn 2.1.0 doesn't install from tar.gz with Python 2.7 (setuptools problem)

### ISSUE THREAD

**Issue by gerph** [unicorn-engine/unicorn#2008]
# Summary

Installing Unicorn for Python 2.7 fails when installing with Python 2.7 when the tar.gz is used. This will happen on any platform which does not already have a suitable wheel present. It would also be seen if a version of `pip` prior to the introduction of the wheel architecture changes is installed (eg around 19.x or earlier).

This might not be a big deal as there may already be versions present for all the major OS versions that are supported, but it's a thing that currently happens.

As such this is probably not a very important bug.

# Steps to provoke

* `docker run -it --rm ubuntu:18.04`
* `apt-get update && apt-get install -y python python-pip`
* `pip install --no-binary :all: -U unicorn`

# Failing output

```
root@1f1c3e7f8599:/# pip install --no-binary :all: -U unicorn
Collecting unicorn
  Downloading https://files.pythonhosted.org/packages/44/87/6e4710dee0716c7d75ad759ee0bbe7ae2d73624c5722749b4d7d55055a43/unicorn-2.1.0.tar.gz (2.8MB)
    100% |################################| 2.8MB 345kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PyeJCM/unicorn/setup.py", line 16, in <module>
        from setuptools.command.build import build
    ImportError: No module named build
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PyeJCM/unicorn/
```

# Expected behaviour

You would expect it to build and install the package.

**Comment by wtdcode** [comment]
This shall be fixed by `pip instlal -U pip wheel setuptools` ?

**Comment by wtdcode** [comment]
Oh yes, you are correct. I understand the context.

Maybe this can be fixed by using egg, but as you suggested, the priority won't be very high.

**Comment by wtdcode** [comment]
Closing as 2.1.2 is out.
