### ISSUE TITLE
missing cmake/bundle_static.cmake when installing unicorn on MacOS 14.5 x86_64

### ISSUE THREAD

**Issue by mustime** [unicorn-engine/unicorn#2015]
install unicorn 2.1.1 with command `pip3 install -i https://pypi.python.org/simple unicorn==2.1.1` and error occurs:

```
Looking in indexes: https://pypi.python.org/simple
Collecting unicorn==2.1.1
  Using cached unicorn-2.1.1.tar.gz (2.8 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: unicorn
  Building wheel for unicorn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      running bdist_wheel
      running build
      Building C extensions
      -- The C compiler identification is AppleClang 15.0.0.15000309
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      CMake Error at CMakeLists.txt:58 (include):
        include could not find requested file:
      
          cmake/bundle_static.cmake
      
      
      Disabling PIE due to missing toolchain support
      /private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-b3f1cs4h/unicorn_4c142ec54a5a4367abfb16c83844c121/src/qemu/configure: line 2177:  9783 Segmentation fault: 11  $TMPE
      Install prefix    /usr/local
      binary directory  /usr/local/bin
      library directory /usr/local/lib
      libexec directory /usr/local/libexec
      include directory /usr/local/include
      config directory  /usr/local/etc
      local state directory   /usr/local/var
      ELF interp prefix /usr/gnemul/qemu-%M
      Build directory   /private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-b3f1cs4h/unicorn_4c142ec54a5a4367abfb16c83844c121/src/build_python
      Source path       /private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-b3f1cs4h/unicorn_4c142ec54a5a4367abfb16c83844c121/src/qemu
      GIT binary        git
      GIT submodules
      C compiler        /usr/bin/cc
      Host C compiler   cc
      C++ compiler      c++
      Objective-C compiler clang
      ARFLAGS           rv
      CFLAGS            -g
      QEMU_CFLAGS       -m64 -mcx16 -DOS_OBJECT_USE_OBJC=0 -arch x86_64 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -std=gnu99  -DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARM64 -DUNICORN_HAS_M68K -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -DUNICORN_HAS_PPC -DUNICORN_HAS_RISCV -DUNICORN_HAS_S390X -DUNICORN_HAS_TRICORE -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk  -Wno-string-plus-int -Wno-typedef-redefinition -Wno-initializer-overrides -Wexpansion-to-defined -Wendif-labels -Wno-shift-negative-value -Wno-missing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-definition -Wtype-limits -fstack-protector-strong
      QEMU_LDFLAGS      -m64 -framework CoreFoundation -framework IOKit -arch x86_64  -DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARM64 -DUNICORN_HAS_M68K -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -DUNICORN_HAS_PPC -DUNICORN_HAS_RISCV -DUNICORN_HAS_S390X -DUNICORN_HAS_TRICORE -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk  -fstack-protector-strong
      make              make
      install           install
      host CPU          x86_64
      host big endian   no
      target list       x86_64-softmmu  arm-softmmu  aarch64-softmmu  m68k-softmmu  mips-softmmu  mipsel-softmmu  mips64-softmmu  mips64el-softmmu  sparc-softmmu  sparc64-softmmu  ppc-softmmu  ppc64-softmmu  riscv32-softmmu  riscv64-softmmu  s390x-softmmu  tricore-softmmu
      strip binaries    yes
      static build      no
      mingw32 support   no
      PIE               no
      TCG support       yes
      malloc trim support no
      membarrier        no
      madvise           yes
      posix_madvise     yes
      posix_memalign    yes
      debug stack usage no
      tcmalloc support  no
      jemalloc support  no
      avx2 optimization no
      avx512f optimization no
      CMake Error at CMakeLists.txt:1432 (bundle_static_library):
        Unknown CMake command "bundle_static_library".
      
      
      -- Configuring incomplete, errors occurred!
```

The error indicates file `cmake/bundle_static.cmake` is unable to be found. Any suggestion on it?

**Comment by wtdcode** [comment]
Look like we missed this file. Why not installing with the wheel?

**Comment by mustime** [comment]
> Look like we missed this file. Why not installing with the wheel?

Yes, I finally install it by manually downloaded whl file.
Just wonder I might not the only one encountering this error.

**Comment by wtdcode** [comment]
> > Look like we missed this file. Why not installing with the wheel?
> 
> Yes, I finally install it by manually downloaded whl file. Just wonder I might not the only one encountering this error.

It's weird. pypi should select the wheel automatically.

Unfortunately, I don't have an x86_64 macros to verify. Could you go with `pip3 install --only-binary=:all: unicorn` ?

**Comment by mustime** [comment]
I tried it like this:
```bash
```

**Comment by mustime** [comment]
I tried it as following:
```bash
pip3 uninstall unicorn
pip3 install -i https://pypi.python.org/simple --only-binary=:all unicorn
```

And still geting the same error:
```
Collecting unicorn
  Using cached unicorn-2.1.1.tar.gz (2.8 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: unicorn
  Building wheel for unicorn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      running bdist_wheel
      running build
      Building C extensions
      -- The C compiler identification is AppleClang 15.0.0.15000309
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      CMake Error at CMakeLists.txt:58 (include):
        include could not find requested file:
      
          cmake/bundle_static.cmake
      
      
      Disabling PIE due to missing toolchain support
      /private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-fylgqlfl/unicorn_6011ecd07c23490886a9ef9b83e5a49d/src/qemu/configure: line 2177: 19907 Segmentation fault: 11  $TMPE
      Install prefix    /usr/local
      binary directory  /usr/local/bin
      library directory /usr/local/lib
      libexec directory /usr/local/libexec
      include directory /usr/local/include
      config directory  /usr/local/etc
      local state directory   /usr/local/var
      ELF interp prefix /usr/gnemul/qemu-%M
      Build directory   /private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-fylgqlfl/unicorn_6011ecd07c23490886a9ef9b83e5a49d/src/build_python
      Source path       /private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-fylgqlfl/unicorn_6011ecd07c23490886a9ef9b83e5a49d/src/qemu
      GIT binary        git
      GIT submodules
      C compiler        /usr/bin/cc
      Host C compiler   cc
      C++ compiler      c++
      Objective-C compiler clang
      ARFLAGS           rv
      CFLAGS            -g
      QEMU_CFLAGS       -m64 -mcx16 -DOS_OBJECT_USE_OBJC=0 -arch x86_64 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -std=gnu99  -DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARM64 -DUNICORN_HAS_M68K -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -DUNICORN_HAS_PPC -DUNICORN_HAS_RISCV -DUNICORN_HAS_S390X -DUNICORN_HAS_TRICORE -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk  -Wno-string-plus-int -Wno-typedef-redefinition -Wno-initializer-overrides -Wexpansion-to-defined -Wendif-labels -Wno-shift-negative-value -Wno-missing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-definition -Wtype-limits -fstack-protector-strong
      QEMU_LDFLAGS      -m64 -framework CoreFoundation -framework IOKit -arch x86_64  -DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARM64 -DUNICORN_HAS_M68K -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -DUNICORN_HAS_PPC -DUNICORN_HAS_RISCV -DUNICORN_HAS_S390X -DUNICORN_HAS_TRICORE -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk  -fstack-protector-strong
      make              make
      install           install
      host CPU          x86_64
      host big endian   no
      target list       x86_64-softmmu  arm-softmmu  aarch64-softmmu  m68k-softmmu  mips-softmmu  mipsel-softmmu  mips64-softmmu  mips64el-softmmu  sparc-softmmu  sparc64-softmmu  ppc-softmmu  ppc64-softmmu  riscv32-softmmu  riscv64-softmmu  s390x-softmmu  tricore-softmmu
      strip binaries    yes
      static build      no
      mingw32 support   no
      PIE               no
      TCG support       yes
      malloc trim support no
      membarrier        no
      madvise           yes
      posix_madvise     yes
      posix_memalign    yes
      debug stack usage no
      tcmalloc support  no
      jemalloc support  no
      avx2 optimization no
      avx512f optimization no
      CMake Error at CMakeLists.txt:1432 (bundle_static_library):
        Unknown CMake command "bundle_static_library".
      
      
      -- Configuring incomplete, errors occurred!
      See also "/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-fylgqlfl/unicorn_6011ecd07c23490886a9ef9b83e5a49d/src/build_python/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-fylgqlfl/unicorn_6011ecd07c23490886a9ef9b83e5a49d/setup.py", line 235, in <module>
          setup(
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-fylgqlfl/unicorn_6011ecd07c23490886a9ef9b83e5a49d/setup.py", line 167, in run
          build_libraries()
        File "/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-fylgqlfl/unicorn_6011ecd07c23490886a9ef9b83e5a49d/setup.py", line 144, in build_libraries
          subprocess.check_call(cmake_args)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-B', '/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-fylgqlfl/unicorn_6011ecd07c23490886a9ef9b83e5a49d/src/build_python', '-S', '/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-fylgqlfl/unicorn_6011ecd07c23490886a9ef9b83e5a49d/src', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for unicorn
  Running setup.py clean for unicorn
Failed to build unicorn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (unicorn)
```

**Comment by wtdcode** [comment]
How about `--no-cache-dir`? What's the output of `pip3 install --no-cache-dir --only-binary=:all: unicorn`

**Comment by mustime** [comment]
> How about `--no-cache-dir`? What's the output of `pip3 install --no-cache-dir --only-binary=:all: unicorn`

try with no luck. same error hints.
however, same command but with `unicorn==2.1.0` works fine.

<details>
<summary>full log: pip3 install --no-cache-dir --only-binary=:all: unicorn==2.1.1</summary>
pip3 install -i https://pypi.python.org/simple --no-cache-dir --only-binary=:all unicorn==2.1.1
Looking in indexes: https://pypi.python.org/simple
Collecting unicorn==2.1.1
  Downloading unicorn-2.1.1.tar.gz (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 19.2 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: unicorn
  Building wheel for unicorn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      running bdist_wheel
      running build
      Building C extensions
      -- The C compiler identification is AppleClang 15.0.0.15000309
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      CMake Error at CMakeLists.txt:58 (include):
        include could not find requested file:
      
          cmake/bundle_static.cmake
      
      
      Disabling PIE due to missing toolchain support
      /private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-0axy8ptz/unicorn_e8ec73fd89384cecb8a9e52738213867/src/qemu/configure: line 2177: 25143 Segmentation fault: 11  $TMPE
      Install prefix    /usr/local
      binary directory  /usr/local/bin
      library directory /usr/local/lib
      libexec directory /usr/local/libexec
      include directory /usr/local/include
      config directory  /usr/local/etc
      local state directory   /usr/local/var
      ELF interp prefix /usr/gnemul/qemu-%M
      Build directory   /private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-0axy8ptz/unicorn_e8ec73fd89384cecb8a9e52738213867/src/build_python
      Source path       /private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-0axy8ptz/unicorn_e8ec73fd89384cecb8a9e52738213867/src/qemu
      GIT binary        git
      GIT submodules
      C compiler        /usr/bin/cc
      Host C compiler   cc
      C++ compiler      c++
      Objective-C compiler clang
      ARFLAGS           rv
      CFLAGS            -g
      QEMU_CFLAGS       -m64 -mcx16 -DOS_OBJECT_USE_OBJC=0 -arch x86_64 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -std=gnu99  -DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARM64 -DUNICORN_HAS_M68K -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -DUNICORN_HAS_PPC -DUNICORN_HAS_RISCV -DUNICORN_HAS_S390X -DUNICORN_HAS_TRICORE -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk  -Wno-string-plus-int -Wno-typedef-redefinition -Wno-initializer-overrides -Wexpansion-to-defined -Wendif-labels -Wno-shift-negative-value -Wno-missing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-definition -Wtype-limits -fstack-protector-strong
      QEMU_LDFLAGS      -m64 -framework CoreFoundation -framework IOKit -arch x86_64  -DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARM64 -DUNICORN_HAS_M68K -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -DUNICORN_HAS_PPC -DUNICORN_HAS_RISCV -DUNICORN_HAS_S390X -DUNICORN_HAS_TRICORE -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk  -fstack-protector-strong
      make              make
      install           install
      host CPU          x86_64
      host big endian   no
      target list       x86_64-softmmu  arm-softmmu  aarch64-softmmu  m68k-softmmu  mips-softmmu  mipsel-softmmu  mips64-softmmu  mips64el-softmmu  sparc-softmmu  sparc64-softmmu  ppc-softmmu  ppc64-softmmu  riscv32-softmmu  riscv64-softmmu  s390x-softmmu  tricore-softmmu
      strip binaries    yes
      static build      no
      mingw32 support   no
      PIE               no
      TCG support       yes
      malloc trim support no
      membarrier        no
      madvise           yes
      posix_madvise     yes
      posix_memalign    yes
      debug stack usage no
      tcmalloc support  no
      jemalloc support  no
      avx2 optimization no
      avx512f optimization no
      CMake Error at CMakeLists.txt:1432 (bundle_static_library):
        Unknown CMake command "bundle_static_library".
      
      
      -- Configuring incomplete, errors occurred!
      See also "/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-0axy8ptz/unicorn_e8ec73fd89384cecb8a9e52738213867/src/build_python/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-0axy8ptz/unicorn_e8ec73fd89384cecb8a9e52738213867/setup.py", line 235, in <module>
          setup(
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-0axy8ptz/unicorn_e8ec73fd89384cecb8a9e52738213867/setup.py", line 167, in run
          build_libraries()
        File "/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-0axy8ptz/unicorn_e8ec73fd89384cecb8a9e52738213867/setup.py", line 144, in build_libraries
          subprocess.check_call(cmake_args)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-B', '/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-0axy8ptz/unicorn_e8ec73fd89384cecb8a9e52738213867/src/build_python', '-S', '/private/var/folders/h1/03999l751t5_mx_xczfng94c0000gn/T/pip-install-0axy8ptz/unicorn_e8ec73fd89384cecb8a9e52738213867/src', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for unicorn
  Running setup.py clean for unicorn
Failed to build unicorn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (unicorn)
</details>

<details>
<summary>full log: pip3 install --no-cache-dir --only-binary=:all: unicorn==2.1.0</summary>
pip3 install -i https://pypi.python.org/simple --no-cache-dir --only-binary=:all unicorn==2.1.0
Collecting unicorn==2.1.0
  Downloading unicorn-2.1.0-py2.py3-none-macosx_10_9_universal2.whl.metadata (1.3 kB)
Downloading unicorn-2.1.0-py2.py3-none-macosx_10_9_universal2.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 17.4 kB/s eta 0:00:00
Installing collected packages: unicorn
Successfully installed unicorn-2.1.0
</details>

**Comment by wtdcode** [comment]
I need to find an x86_64 macOS to see why it breaks. We will release 2.1.2 shortly to reflect a series of fixes.

**Comment by wtdcode** [comment]
Fixed by including `cmake` directory in 7e328647742f1a93c670e5b2ba6d8012dda2c1b7 and wheels will be fixed by #2026

**Comment by wtdcode** [comment]
Closing as #2026 gets fixed.
