### ISSUE TITLE
Fix Python regression failures

### ISSUE THREAD

**Issue by elicn** [unicorn-engine/unicorn#2038]
Three of the Python regression tests are still failing (using `dev` commit 3691e33a).
Reproduce by running:
```sh
python3 $UCHOME/tests/regress/regress.py
```
Output:
```
[INFO] starting discovery
[INFO] 66 test modules found
[INFO] 85 test cases were added
........F................................F.................F.........................
======================================================================
FAIL: runTest (jumping.Jumping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elicn/Downloads/unicorn/tests/regress/jumping.py", line 123, in runTest
    self.assertEqual(self.uc.reg_read(UC_X86_REG_RDX), 0xbabe, "rdx contains the wrong value. eflags modification failed")
AssertionError: 49354 != 47806 : rdx contains the wrong value. eflags modification failed

======================================================================
FAIL: runTest (sparc_reg.TestSparcRegRead)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elicn/Downloads/unicorn/tests/regress/sparc_reg.py", line 103, in runTest
    self.assertEqual(4 * 32, uc.reg_read(UC_SPARC_REG_PC))  # make sure we executed all instructions
AssertionError: 128 != 4

======================================================================
FAIL: runTest (mips_except.MipsExcept)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elicn/Downloads/unicorn/tests/regress/mips_except.py", line 36, in runTest
    self.assertEqual(UC_ERR_READ_UNALIGNED, m.exception.errno)
AssertionError: 16 != 21

----------------------------------------------------------------------
Ran 85 tests in 13.830s

FAILED (failures=3)
```

**Comment by wtdcode** [comment]
Noted, will have a look before 2.1.2

**Comment by wtdcode** [comment]
All regressions should be addressed!
