### ISSUE TITLE
2.1.1 fails to import on Python 3.8

### ISSUE THREAD

**Issue by peace-maker** [unicorn-engine/unicorn#2061]
While trying to use unicorn 2.1.1 on an Ubuntu 20.04 install which uses Python 3.8, it installs fine but fails to import.

```
>>> import unicorn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, ucsubclass, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 14, in <module>
    from .unicorn_py3 import *
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn_py3/__init__.py", line 1, in <module>
    from .unicorn import *
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn_py3/unicorn.py", line 200, in <module>
    uclib = __load_uc_lib()
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn_py3/unicorn.py", line 99, in __load_uc_lib
    resources.files("unicorn") / 'lib'
AttributeError: module 'importlib.resources' has no attribute 'files'
```

If Python 3.8 is supposed to be still supported (Ubuntu 20.04 is EOL in April 2025, while Python 3.8 was EOL at September 2024 -.-), then https://github.com/unicorn-engine/unicorn/commit/1e04dbf83bbb22245dff329fe7eeeacf244650e5 introduced a regression, because  [`importlib.resources.files`](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files) was added in Python 3.9. The except block would need to catch `AttributeError`s too next to `ImportError`.

**Comment by wtdcode** [comment]
This is aware and already fixed in dev branch.
________________________________
From: peace-maker ***@***.***>
Sent: Friday, December 6, 2024 12:09:16 AM
To: unicorn-engine/unicorn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicorn-engine/unicorn] 2.1.1 fails to import on Python 3.8 (Issue #2061)


While trying to use unicorn 2.1.1 on an Ubuntu 20.04 install which uses Python 3.8, it installs fine but fails to import.

>>> import unicorn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, ucsubclass, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 14, in <module>
    from .unicorn_py3 import *
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn_py3/__init__.py", line 1, in <module>
    from .unicorn import *
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn_py3/unicorn.py", line 200, in <module>
    uclib = __load_uc_lib()
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn_py3/unicorn.py", line 99, in __load_uc_lib
    resources.files("unicorn") / 'lib'
AttributeError: module 'importlib.resources' has no attribute 'files'


If Python 3.8 is supposed to be still supported (Ubuntu 20.04 is EOL in April 2025, while Python 3.8 was EOL at September 2024 -.-), then 1e04dbf<https://github.com/unicorn-engine/unicorn/commit/1e04dbf83bbb22245dff329fe7eeeacf244650e5> introduced a regression, because importlib.resources.files<https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files> was added in Python 3.9. The except block would need to catch AttributeErrors too next to ImportError.

―

**Comment by huaerxiela** [comment]
i switch to use unicorn==2.1.0 on python3.8🤦‍

**Comment by wtdcode** [comment]
Closing as 2.1.2 is out.
