### ISSUE TITLE
Unicorn ARM problems

### ISSUE THREAD

**Issue by petevine** [unicorn-engine/unicorn#382]
I've just managed to build unicorn on ARM by using just a single architecture:

` UNICORN_ARCHS="x86" make.sh`

However, while building the samples we immediately get a hint something's wrong:

```shell
LINK    sample_x86
../libunicorn.so: error: undefined reference to 'qemu_getauxval'
../libunicorn.so: error: undefined reference to 'pthread_mutexattr_init'
../libunicorn.so: error: undefined reference to 'pthread_mutexattr_settype'
../libunicorn.so: error: undefined reference to 'pthread_mutexattr_destroy'
../libunicorn.so: error: undefined reference to 'pthread_mutex_trylock'
../libunicorn.so: error: undefined reference to 'sem_init'
../libunicorn.so: error: undefined reference to 'sem_destroy'
../libunicorn.so: error: undefined reference to 'sem_post'
../libunicorn.so: error: undefined reference to 'sem_trywait'
../libunicorn.so: error: undefined reference to 'sem_timedwait'
../libunicorn.so: error: undefined reference to 'sem_wait'
../libunicorn.so: error: undefined reference to 'pthread_sigmask'
../libunicorn.so: error: undefined reference to 'pthread_create'
../libunicorn.so: error: undefined reference to 'pthread_join'
../libunicorn.so: error: undefined reference to 'pthread_kill'
````

For some reason `LDFLAGS=-lpthread` needs to be exported manually which leaves:

**undefined reference to 'qemu_getauxval'**

Naturally, the installed library doesn't work:

```python
/tmp/unicorn/bindings/python/sample_x86.py
Traceback (most recent call last):
  File "/tmp/unicorn/bindings/python/sample_x86.py", line 5, in <module>
    from unicorn import *
  File "/tmp/unicorn/bindings/python/unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "/tmp/unicorn/bindings/python/unicorn/unicorn.py", line 81, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
````

What gives?

**Comment by petevine** [comment]
cc: @lunixbochs

**Comment by aquynh** [comment]
i removed file util/getauxval.c from Qemu when i forked Unicorn, but apparently this is needed for ARM backend. so you should recover this file from Qemu 2.2.1 version and try to put it back.

you can recover the other missing files if you still cannot compile. 

thanks.

**Comment by petevine** [comment]
I managed to compile so to get that symbol back would have to entail modifying the Makefiles, right?

**Comment by petevine** [comment]
Never mind, that's what you meant obviously.

**Comment by petevine** [comment]
Hooray, I've got it working on ARM!

I added the missing file and the following line to `qemu/util/Makefile.objs`:

`util-obj-y += getauxval.o`

and that was enough. Thanks.

**Comment by aquynh** [comment]
Nice, so all samples/sample_xxx compiled and worked on ARM without any
issue?

**Comment by petevine** [comment]
We still have the original problem of not able to link all architectures in at the same time. I worked around it by enabling just x86 and that works as expected. Plus all samples compile fine as well.

I'm pretty sure this should work for any of the remaining archs separately.

**Comment by aquynh** [comment]
can you paste the output error when compiling on ARM with default option? (just run `./make.sh` is enough)

**Comment by petevine** [comment]
Sure, it seems it manages to get to the linking stage nowadays:

````
 GEN     ./libunicorn.so.0
/usr/bin/ld.gold.real: error: qemu/arm-softmmu/tcg/tcg.o: multiple definition of 'use_idiv_instructions'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/arm-softmmu/tcg/tcg.o: multiple definition of 'tcg_target_deposit_valid'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/m68k-softmmu/tcg/tcg.o: multiple definition of 'use_idiv_instructions'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/m68k-softmmu/tcg/tcg.o: multiple definition of 'tcg_target_deposit_valid'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/aarch64-softmmu/tcg/tcg.o: multiple definition of 'use_idiv_instructions'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/aarch64-softmmu/tcg/tcg.o: multiple definition of 'tcg_target_deposit_valid'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/mips-softmmu/tcg/tcg.o: multiple definition of 'use_idiv_instructions'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/mips-softmmu/tcg/tcg.o: multiple definition of 'tcg_target_deposit_valid'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/mipsel-softmmu/tcg/tcg.o: multiple definition of 'use_idiv_instructions'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/mipsel-softmmu/tcg/tcg.o: multiple definition of 'tcg_target_deposit_valid'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/mips64-softmmu/tcg/tcg.o: multiple definition of 'use_idiv_instructions'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/mips64-softmmu/tcg/tcg.o: multiple definition of 'tcg_target_deposit_valid'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/mips64el-softmmu/tcg/tcg.o: multiple definition of 'use_idiv_instructions'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/mips64el-softmmu/tcg/tcg.o: multiple definition of 'tcg_target_deposit_valid'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/sparc-softmmu/tcg/tcg.o: multiple definition of 'use_idiv_instructions'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/sparc-softmmu/tcg/tcg.o: multiple definition of 'tcg_target_deposit_valid'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/sparc64-softmmu/tcg/tcg.o: multiple definition of 'use_idiv_instructions'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
/usr/bin/ld.gold.real: error: qemu/sparc64-softmmu/tcg/tcg.o: multiple definition of 'tcg_target_deposit_valid'
/usr/bin/ld.gold.real: qemu/x86_64-softmmu/tcg/tcg.o: previous definition here
````

**Comment by aquynh** [comment]
can you pull the new branch "arm" (https://github.com/unicorn-engine/unicorn/tree/arm) and try to compile again on ARM to see if the problem is fixed?

**Comment by petevine** [comment]
Sure, give me a few minutes.

**Comment by petevine** [comment]
Yes, it does compile and link now, but:

````
 LINK    sample_arm
../libunicorn.so: error: undefined reference to 'use_idiv_instructions_mips'
../libunicorn.so: error: undefined reference to 'use_idiv_instructions_mipsel'
````

**Comment by aquynh** [comment]
can you pull from the "arm" branch now and try again?

**Comment by petevine** [comment]
Now it's:

```rust
 LINK    sample_arm
../libunicorn.so: error: undefined reference to 'use_idiv_instructions_rt_mips'
../libunicorn.so: error: undefined reference to 'use_idiv_instructions_rt_mipsel'
````

**Comment by aquynh** [comment]
now can you try again?

**Comment by petevine** [comment]
That did it - all tests pass. Well done and thanks!

**Comment by petevine** [comment]
Oh, one last thing - please have a look the samples' Makefile and the missing `-lpthread`.

Cheers!

**Comment by aquynh** [comment]
missing "-lpthread"? why did you still compile and run the tests successfully?
what is the output error?

**Comment by aquynh** [comment]
i merged the branch "arm" into "master", and deleted "arm".

**Comment by petevine** [comment]
As I pointed out in the first comment, I was passing LDFLAGS manually.

**Comment by aquynh** [comment]
see https://github.com/unicorn-engine/unicorn/commit/69b784fc45fc134438e75e4a8f4b0c56015e509a. can you pull & try to compile again without your trick now?

**Comment by petevine** [comment]
Indeed, the missing link has just got filled :)

**Comment by aquynh** [comment]
now if you can try to see if ARM64 backend works & report the result, that would be great!

**Comment by petevine** [comment]
Can't help with that as I don't have the hardware. Hopefully someone on e.g. Tegra will hear your plea soon.

**Comment by aquynh** [comment]
i added ARM64 backend to the TODO list: https://github.com/unicorn-engine/unicorn/wiki/TODO
