### ISSUE TITLE
AttributeError: dlsym(0x7fde3b42d4d0, uc_mem_map_ptr): symbol not found with homebrew

### ISSUE THREAD

**Issue by tkmru** [unicorn-engine/unicorn#438]
I installed unicorn with homebrew into OS X(El capitan), and used Python binding. 
I imported unicorn module, it resulted AttributeError: dlsym(0x7fde3b42d4d0, uc_mem_map_ptr): symbol not found.

```
>>> import unicorn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "/usr/local/lib/python2.7/site-packages/unicorn/unicorn.py", line 107, in <module>
    _setup_prototype(_uc, "uc_mem_map_ptr", ucerr, uc_engine, ctypes.c_uint64, ctypes.c_size_t, ctypes.c_uint32, ctypes.c_void_p)
  File "/usr/local/lib/python2.7/site-packages/unicorn/unicorn.py", line 86, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fde3b42d4d0, uc_mem_map_ptr): symbol not found
```

I make unicorn with make.sh and import unicorn. It didn't result error.
Maybe, homebrew formula is wrong something.

[homebrew/unicorn.rb at master · Homebrew/homebrew](https://github.com/Homebrew/homebrew/blob/master/Library%2FFormula%2Funicorn.rb)

**Comment by aquynh** [comment]
The reason is that the core of Unicorn from Hombrew is for v0.9, but the Python binding you are using is for newer core, which added some new API recently.

You should always use the bindings coming with the same core to guarantee everything works. Latest code from Github now is quite better than v0.9.

**Comment by tkmru** [comment]
Oh, core is different between Homebrew and github master branch. 
Thanks.

**Comment by tkmru** [comment]
I think master branch must be same version installed by homebrew.
It is better that latest branch is develop branch.

**Comment by aquynh** [comment]
Yes, actually our master branch is a development branch.
