### ISSUE TITLE
Is there a better way to compile target 32-bit binary on 64-bit

### ISSUE THREAD

**Issue by ThomasKing2014** [unicorn-engine/unicorn#482]
When I'm doing a test in IDA6.8, I find that IDAPython needs a 32-bit dylib and libunicorn.1.dylib is not a fat shared library, only with x86_64 architecture. So a error raises from **init**.py of unicorn.
There is no option for nix32 in make.sh. I copy the command line from Capstone and compile. I use libp to create a fat dylib and replace the old one in /usr/local/lib. It works well in C, but python bindings fails. 
Is there a way to build a fat dylib for x86_64 and i386?

python bindings error:

dlsym(0x2bdaf50, uc_version): symbol not found
Traceback (most recent call last):
  File "/Applications/IDA Pro 6.8/idaq.app/Contents/MacOS/python/idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
  File "/Users/thomasking/Desktop/unicorn_test/test.py", line 4, in <module>
    from unicorn import *
  File "/Library/Python/2.7/site-packages/unicorn/**init**.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, **version**
  File "/Library/Python/2.7/site-packages/unicorn/unicorn.py", line 96, in <module>
    _setup_prototype(_uc, "uc_version", ctypes.c_uint, ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int))
  File "/Library/Python/2.7/site-packages/unicorn/unicorn.py", line 89, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in **getattr**
    func = self.**getitem**(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/**init**.py", line 383, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x2bdaf50, uc_version): symbol not found

**Comment by lunixbochs** [comment]
Does the 64-bit IDA launcher use 64-bit Python, where this wouldn't be a problem?

**Comment by cseagle** [comment]
All versions of IDA are built as 32-bit binaries and need 32-bit python. Any other library you want to use from IDA (plugin or python import) also needs to be 32-bit

**Comment by lunixbochs** [comment]
I put `CFLAGS += -arch i386` right after GENOBJ in `unicorn/Makefile` and it successfully built a 32-bit libunicorn.dylib for me.

**Comment by aquynh** [comment]
very cool, @lunixbochs! looks like Unicorn can be used for IDA plugin on OSX thanks to this? should we put this into `make.sh`, so users can compile to 32bit without having to modify Makefile?

**Comment by lunixbochs** [comment]
With some additional tweaks we can probably make Darwin build both (it fails to build object files for both atm).

**Comment by ThomasKing2014** [comment]
@aquynh @lunixbochs 
Indeed, we can make Darwin build both 32-bit and 64-bit into the library. Just add some lines in unicorn/Makefile as following:
1. Add 'CFLAGS += -m32 -arch i386 -m64 -arch x86_64' right after GENOBJ.
2. Add two lines in 'ifeq ($(IS_APPLE),1)' block:
UNICORN_CFLAGS += -m32 -arch i386 -m64 -arch x86_64
$(LIBNAME)_LDFLAGS += -m32 -arch i386 -m64 -arch x86_64

By the way, it may need to update a universal glib using 'brew install glib --universal'

**Comment by aquynh** [comment]
@ThomasKing2014, would you send in a PR?

**Comment by MatrixLing** [comment]
@ThomasKing2014   I get both 32-bit and 64-bit library as your method. But in IDAPython, It has an error. Have you ever encountered this error. I'm not familiar with osx library, so I don't know how to solve it. Can you help me? Thanks. 

Python>from unicorn import *
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError
  File "/Library/Python/2.7/site-packages/unicorn/unicorn.py", line 93, in <module>
    _setup_prototype(_uc, "uc_version", ctypes.c_uint, ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int))
  File "/Library/Python/2.7/site-packages/unicorn/unicorn.py", line 86, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/ctypes/__init__.py", line 358, in __getattr__
    func = self.__getitem__(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/ctypes/__init__.py", line 363, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x157a9a30, uc_version): symbol not found

**Comment by aquynh** [comment]
just pushed a commit to build universal binaries on MacOS by default: https://github.com/unicorn-engine/unicorn/commit/eea0b2d520dd3d40f35fa887913066d6e413a5a2

thank you, @ThomasKing2014
