### ISSUE TITLE
Unicorn Requests 300MiB+ RAM Chunk

### ISSUE THREAD

**Issue by zachriggle** [unicorn-engine/unicorn#487]
Unicorn can't load on low-memory systems because it requests a huge chunk of memory.

```
$ strace -emmap,mmap2 python
...
>>> import unicorn
...
mmap(NULL, 347622000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 5, 0) = 0x7fd4e4c39000
mmap(0x7fd4e5757000, 421888, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 5, 0x91e000) = 0x7fd4e5757000
mmap(0x7fd4e57be000, 335542896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fd4e57be000
mmap(NULL, 3175976, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 5, 0) = 0x7fd4e4931000
mmap(0x7fd4e4c36000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 5, 0x105000) = 0x7fd4e4c36000
mmap(0x7fd4e4c38000, 1576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fd4e4c38000
mmap(NULL, 2347200, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 5, 0) = 0x7fd4e46f3000
mmap(0x7fd4e492f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 5, 0x3c000) = 0x7fd4e492f000
```

Notice the request for 335542896 bytes (~320MiB).

```
mmap(0x7fd4e57be000, 335542896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fd4e57be000
```

This causes issues when running on low-memory systems that manifest in this manner:

```
Traceback (most recent call last):
  File "/home/zerocool/pwndbg/gdbinit.py", line 10, in <module>
    import pwndbg
  File "/home/zerocool/pwndbg/pwndbg/__init__.py", line 13, in <module>
    import pwndbg.emu
  File "/home/zerocool/pwndbg/pwndbg/emu/__init__.py", line 2, in <module>
    import pwndbg.emu.x86
  File "/home/zerocool/pwndbg/pwndbg/emu/x86.py", line 2, in <module>
    import pwndbg.emu.emulator
  File "/home/zerocool/pwndbg/pwndbg/emu/emulator.py", line 6, in <module>
    import unicorn as U
  File "/usr/local/lib/python3.4/dist-packages/unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
  File "/usr/local/lib/python3.4/dist-packages/unicorn/unicorn.py", line 81, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```

You can see the specific error by manually loading the library:

```
>>> ctypes.cdll.LoadLibrary('libunicorn.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/ctypes/__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libunicorn.so: cannot map zero-fill pages: Cannot allocate memory
```

**Comment by aquynh** [comment]
A single call to "import unicorn" raises this issue?

Can you trace back to the source to see where mmap() is called with so much memory?

**Comment by zachriggle** [comment]
Looks like it's just what's declared in the binary.

```
$ readelf -l /usr/lib/libunicorn.so.1

Elf file type is DYN (Shared object file)
Entry point 0x6af80
There are 5 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000009170dc 0x00000000009170dc  R E    200000
  LOAD           0x00000000009170e0 0x0000000000b170e0 0x0000000000b170e0
                 0x00000000000651c0 0x0000000014065440  RW     200000 <=============== Huge
  DYNAMIC        0x000000000096fa00 0x0000000000b6fa00 0x0000000000b6fa00
                 0x00000000000001f0 0x00000000000001f0  RW     8
  GNU_EH_FRAME   0x000000000080efa4 0x000000000080efa4 0x000000000080efa4
                 0x0000000000034ce4 0x0000000000034ce4  R      4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     10
```

**Comment by zachriggle** [comment]
Looks like the culprit is `static_code_gen_buffer` which has 10 instances and each takes up 30MB.

```
Symbol table '.symtab' contains 28205 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
  1650: 0000000000b7c2d0 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
  3911: 0000000002b7c3a0 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
  4813: 0000000004b7c3d0 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
  7440: 0000000006b7c400 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
  9390: 0000000008b7c430 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
 11339: 000000000ab7c460 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
 13450: 000000000cb7c490 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
 15555: 000000000eb7c4c0 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
 16570: 0000000010b7c4f0 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
 17774: 0000000012b7c520 0x2000000 OBJECT  LOCAL  DEFAULT   23 static_code_gen_buffer
```

**Comment by zachriggle** [comment]
Yep.

```
$ ag -C3 DEFAULT_CODE_GEN_BUFFER_SIZE
qemu/translate-all.c
501-# define MAX_CODE_GEN_BUFFER_SIZE  ((size_t)-1)
502-#endif
503-
504:#define DEFAULT_CODE_GEN_BUFFER_SIZE_1 (32u * 1024 * 1024)
505-
506:#define DEFAULT_CODE_GEN_BUFFER_SIZE \
507:  (DEFAULT_CODE_GEN_BUFFER_SIZE_1 < MAX_CODE_GEN_BUFFER_SIZE \
508:   ? DEFAULT_CODE_GEN_BUFFER_SIZE_1 : MAX_CODE_GEN_BUFFER_SIZE)
509-
510-static inline size_t size_code_gen_buffer(struct uc_struct *uc, size_t tb_size)
511-{
--
514-    /* Size the buffer.  */
515-    if (tb_size == 0) {
516-#ifdef USE_STATIC_CODE_GEN_BUFFER
517:        tb_size = DEFAULT_CODE_GEN_BUFFER_SIZE;
518-#else
519-        /* ??? Needs adjustments.  */
520-        /* ??? If we relax the requirement that CONFIG_USER_ONLY use the
--
562-#endif
563-
564-#ifdef USE_STATIC_CODE_GEN_BUFFER
565:static uint8_t static_code_gen_buffer[DEFAULT_CODE_GEN_BUFFER_SIZE]
566-    __attribute__((aligned(CODE_GEN_ALIGN)));
567-
568-static inline void *alloc_code_gen_buffer(struct uc_struct *uc)
```

**Comment by lunixbochs** [comment]
`qemu/translate-all.c` has `#define DEFAULT_CODE_GEN_BUFFER_SIZE_1 (32u * 1024 * 1024)`

    static uint8_t static_code_gen_buffer[DEFAULT_CODE_GEN_BUFFER_SIZE]
        __attribute__((aligned(CODE_GEN_ALIGN)));

This is an artifact of compiling a separate copy of the TCG code for each architecture. It's just the executable block TCG uses as output. Maybe we can share that symbol and metadata between TCG instances.

**Comment by cseagle** [comment]
Caveat, I really have no idea how the tcg works. Can it be shared for example if I have instantiated an arm instance and an x86 instance within the same program? Is there any reason not to dynamically allocate the buffer at the first uc_open for each architecture?

**Comment by zachriggle** [comment]
> Is there any reason

There is no reason in QEMU ;)

**Comment by lunixbochs** [comment]
I think the static code buffer only exists to eliminate the need to call mmap() on startup in qemu-user. We don't have any related restrictions, so I think it's more reasonable to dynamically allocate.

**Comment by aquynh** [comment]
Yes dynamically allocating this buffer for each Uc instance is a quick solution. The pointer to buffer can be put inside uc_struct. Anyone wants to make a PR for this?

Thanks
