### ISSUE TITLE
Misleading Error Message when Architecture is Unavailable

### ISSUE THREAD

**Issue by zachriggle** [unicorn-engine/unicorn#531]
If you build with `UNICORN_ARCHS='x86'` and then attempt to create an ARM `Uc` object, the error message you get is: `exception str() failed`.

```
>>> pwndbg.emu.emulator.Emulator()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/pwndbg/pwndbg/emu/emulator.py", line 105, in __init__
    self.uc = U.Uc(arch_to_UC[self.arch], self.mode)
  File "/usr/local/lib/python3.5/dist-packages/unicorn/unicorn.py", line 215, in __init__
    raise UcError(status)
unicorn.unicorn.UcError: <exception str() failed>
```

**Comment by aquynh** [comment]
something is wrong in your code? here is what i get:

```
$ UNICORN_ARCHS="x86" ./make.sh
....

$ sudo UNICORN_ARCHS="x86" ./make.sh install
...

$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from unicorn import *
>>> uc = Uc(UC_ARCH_ARM, UC_MODE_ARM)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/unicorn/unicorn.py", line 215, in __init__
    raise UcError(status)
unicorn.unicorn.UcError: Invalid/unsupported architecture (UC_ERR_ARCH)

```

**Comment by aquynh** [comment]
close, thanks!
