### ISSUE TITLE
AttributeError: dlsym - Symbol not found

### ISSUE THREAD

**Issue by coolandsmartrr** [unicorn-engine/unicorn#555]
I've install nfcpy via pip, but am struggling to set it up. While running in the python shell, the following error comes up:

    >>> import nfc
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/nfc/__init__.py", line 28, in <module>
        from clf import ContactlessFrontend
      File "/usr/local/lib/python2.7/site-packages/nfc/clf/__init__.py", line 34, in <module>
        import nfc.llcp
      File "/usr/local/lib/python2.7/site-packages/nfc/llcp/__init__.py", line 31, in <module>
        from llc import LOGICAL_DATA_LINK, DATA_LINK_CONNECTION
      File "/usr/local/lib/python2.7/site-packages/nfc/llcp/llc.py", line 41, in <module>
        from . import sec
      File "/usr/local/lib/python2.7/site-packages/nfc/llcp/sec.py", line 490, in <module>
        OpenSSL = OpenSSLWrapper(libcrypto)
      File "/usr/local/lib/python2.7/site-packages/nfc/llcp/sec.py", line 183, in __init__
        self.crypto.EC_KEY_set_public_key_affine_coordinates.restype = c_int
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
        func = self.__getitem__(name)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(0x7f81ca493370, EC_KEY_set_public_key_affine_coordinates): symbol not found

What's the meaning of this error message, and how could it be fixed?

For reference, I am using the following configuration:

- OS: Mac OSX 10.10.5

- NFC Reader: RC-S380

- Python 2.7.10

- pip 8.1.2

- nfcpy (0.11.1)

**Comment by lunixbochs** [comment]
You should try installing a newer version of OpenSSL (maybe from homebrew), and also try posting issues on the right project. Unicorn is a CPU emulator and has basically nothing to do with NFC :)

**Comment by aquynh** [comment]
close, thanks!
